services:
  jekyll:
    build: .
    ports:
      - "4000:4000"
      - "35729:35729"
    volumes:
      - .:/site:z
      - bundle:/usr/local/bundle
    environment:
      - JEKYLL_ENV=development
    user: "${UID:-1000}:${GID:-1000}"

volumes:
  bundle:
